highlighter:      rouge
# Permalinks
permalink:        pretty

# Setup
title:            Jyt0532
tagline:          'A Jekyll theme'
description:      'Life of an engineer in SV.'
url:              https://jyt0532.github.io
baseurl:          /blog/

author:
  name:           'Bo-Yu Chiang'
  url:            https://twitter.com/jyt0532

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
  repo:           https://github.com/jyt0532/blog
